// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa23AZ2OBJASKcAN2MGCqc7jvXgHHu8xM',
    appId: '1:377718802756:web:876bed214a8c4bf1962f11',
    messagingSenderId: '377718802756',
    projectId: 'nragroup-kar-pro',
    authDomain: 'nragroup-kar-pro.firebaseapp.com',
    storageBucket: 'nragroup-kar-pro.firebasestorage.app',
    measurementId: 'G-YGSSM2PH7K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdxev9HGPyUMov3JThzROzIq7HGUgZSxc',
    appId: '1:377718802756:android:0e2afb81b9e47d62962f11',
    messagingSenderId: '377718802756',
    projectId: 'nragroup-kar-pro',
    storageBucket: 'nragroup-kar-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwYjxS5xI6-jbKK0m2TBAtNaVAoZKjtMk',
    appId: '1:377718802756:ios:c3bfa492ea891948962f11',
    messagingSenderId: '377718802756',
    projectId: 'nragroup-kar-pro',
    storageBucket: 'nragroup-kar-pro.firebasestorage.app',
    iosBundleId: 'com.example.nraProKar',
  );
}
